# Generated by Django 4.2.4 on 2023-08-08 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=48)),
                ('order_total', models.CharField(max_length=48)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=48)),
                ('delivery_options', models.CharField(max_length=48)),
                ('delivery_date', models.DateField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_shipments', to='shipping.shipping')),
            ],
        ),
    ]
